version: '3.7'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./external/redis:/data

  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./external/mongo:/data/db